### ISSUE TITLE
Improve Mensa data

### ISSUE THREAD

**Issue by kiliankoe** [HTWDD/htwcampus#21]
As described in https://github.com/HTWDD/htwcampus/commit/21d1e25aa87bb1e16aaca8b37cfd3bc6fb10d1e3#commitcomment-25267480

Android Implementation: https://github.com/HTWDD/HTWDresden/blob/master/app/src/main/java/de/htwdd/htwdresden/types/Meal.java#L60-L73

**Comment by kiliankoe** [comment]
Is it necessary to get meals for anything but the current day? Just threw some rss feed parsing into [StuWeDD](https://github.com/kiliankoe/StuWeDD) to enable fetching of current meal data.

**Comment by BenchR267** [comment]
Does the rss feed for the current day even contain all information? I think it would be great to have additional informations like allergy information as well (which is currently not part of the feed afaik. Maybe even more important: price!

**Comment by kiliankoe** [comment]
Unfortunately ingredients/allergens aren't listed, that's correct 😢 Price is there though.

Will look into the best way of getting as much data as possible 😊
