### ISSUE TITLE
Create widget for schedule

### ISSUE THREAD

**Issue by BenchR267** [HTWDD/htwcampus#29]
Next lesson
view more -> all for this day

**Comment by fabianehlert** [comment]
Current status:
- UserDefaults are not shared across targets

**Comment by BenchR267** [comment]
@fabianehlert fixed in 4cef150

**Comment by BenchR267** [comment]
Any open tasks here? UI could be improved and empty-state is missing. But otherwise it looks fine 🚀

**Comment by BenchR267** [comment]
- [ ] Add empty state to view
