### ISSUE TITLE
Implement "No results" view

### ISSUE THREAD

**Issue by fabianehlert** [HTWDD/htwcampus#56]
- Schedule
- Exams
- Grades
- Canteen

**Comment by fabianehlert** [comment]
Current status:
- NoResultsView subclass has been created and is working
- "Empty detection" in DataSource is working fine
- ! When adding a NoResultsView as a subView of the view property of any of the CollectionViewController classes, large navigation bar titles will stop working.

**Comment by BenchR267** [comment]
Fixed

**Comment by BenchR267** [comment]
Open for discussion: Use an item in the data source instead.
